// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkPpqJTGuew0xmcYcuAUyjSJae0UlbwRU',
    appId: '1:36308256072:web:57a8115d0d2560f8c1df7d',
    messagingSenderId: '36308256072',
    projectId: 'barcode-scanner-72142',
    authDomain: 'barcode-scanner-72142.firebaseapp.com',
    storageBucket: 'barcode-scanner-72142.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnm1LfxmvtP7LEW_R0rCrMUd4wcz0NAOY',
    appId: '1:36308256072:android:41b2a2bb03a8a741c1df7d',
    messagingSenderId: '36308256072',
    projectId: 'barcode-scanner-72142',
    storageBucket: 'barcode-scanner-72142.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9T5JHBOOiTA0x07u6hd2qGSaSxJzGnbM',
    appId: '1:36308256072:ios:8b0bbb87d5c9c80cc1df7d',
    messagingSenderId: '36308256072',
    projectId: 'barcode-scanner-72142',
    storageBucket: 'barcode-scanner-72142.appspot.com',
    iosClientId: '36308256072-1f97lt2ggmam80hcf59a1rg9t3peep44.apps.googleusercontent.com',
    iosBundleId: 'com.example.barcodeReader',
  );
}
